### ISSUE TITLE
Sizes of plots produced by SSTReceptorDemo

### ISSUE THREAD

**Issue by spitschan** [spitschan/SilentSubstitutionToolbox#27]
I needed to make the sizes of the figures produced by SSTReceptorDemo quite a bit larger to avoid overcrowding of the PNG files. I'm not sure if the figure scaling changed in MATLAB R2017a (which I'm running) or if they never had the right size. Would be useful if someone could run the demo in some other MATLAB version and see if the plots look like the one in the repository.

**Comment by DavidBrainard** [comment]
The plots come out OK  in the PNGs – indeed they look very nice.  But, in the Matlab figure windows themselves, Figures 2 and 5 come out very
munged.  Since these are the first things a user sees, it would be nice if they could be resized too, so that they look nice  to someone running
the demo.  This is the same principle that makes me not like warning text in a demo – a new  user’s faith in the code drops when warnings
show up or when figures look munged.

If it is hard to fix the figures in the Matlab windows, plan B is to add comments to the code that makes them, noting this about them and
Indicating that the saved versions should look good.


[cid:image001.png@01D32A21.CEEF4130][cid:image002.png@01D32A21.CEEF4130]

**Comment by spitschan** [comment]
Thanks for checking @DavidBrainard. I added a call that enlargens the munged figures. Would you be so kind to run the demo code on your machine as well and see if it produces adequate results? Just want to make sure whatever I implemented is generalizable, at least to some degree. Thanks.

**Comment by DavidBrainard** [comment]
This look good now!  Closing.
