### ISSUE TITLE
ReceptorIsolateDemo fails for the 'Dog' case

### ISSUE THREAD

**Issue by spitschan** [spitschan/SilentSubstitutionToolbox#3]
Running `ReceptorIsolateDemo` fails when selecting the 'Dog' receptors with the following error message:

```
Error using load
Unable to read file 'T_dogrec'. No such file or directory.
```

I can't find this file in PTB. @DavidBrainard do you know where this lives?

**Comment by DavidBrainard** [comment]
That file was in PsychCalLocalData, which seems like a screwy place for it.  I moved it into PTB, so this should now work.

Also, I updated the SilentSubstitutionToolbox to "include" BrainardLabToolbox and PsychToolbox, rather than to directly specify them on gitHub.  This causes the code to find out how to get these by looking for their configuration files, so if we were ever to move one, we would only have to update in one configuration file (for example, if PTB moved, we'd just update Psychtoolbox3.json and not have to touch anything that included it.)
